# Generated by Django 5.1.3 on 2024-11-28 14:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='CEDULA: ')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del empleado : ')),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('ruc', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la empresa : ')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Empresas',
            },
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, validators=[django.core.validators.MinLengthValidator(60)]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_factura', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=True, editable=False, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=True, editable=False, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=True, editable=False, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventasapp.clientes')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventasapp.empleados')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventasapp.productos')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=10, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del proveedor : ')),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventasapp.empresas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
            },
        ),
    ]
